# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: release-1.26
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from kubernetes.client.models.v1alpha1_pod_scheduling_spec import V1alpha1PodSchedulingSpec

class TestV1alpha1PodSchedulingSpec(unittest.TestCase):
    """V1alpha1PodSchedulingSpec unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1alpha1PodSchedulingSpec:
        """Test V1alpha1PodSchedulingSpec
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1alpha1PodSchedulingSpec`
        """
        model = V1alpha1PodSchedulingSpec()
        if include_optional:
            return V1alpha1PodSchedulingSpec(
                potential_nodes = [
                    ''
                    ],
                selected_node = ''
            )
        else:
            return V1alpha1PodSchedulingSpec(
        )
        """

    def testV1alpha1PodSchedulingSpec(self):
        """Test V1alpha1PodSchedulingSpec"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
