# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: release-1.26
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from kubernetes.client.api.storage_v1beta1_api import StorageV1beta1Api


class TestStorageV1beta1Api(unittest.TestCase):
    """StorageV1beta1Api unit test stubs"""

    def setUp(self) -> None:
        self.api = StorageV1beta1Api()

    def tearDown(self) -> None:
        pass

    def test_create_namespaced_csi_storage_capacity(self) -> None:
        """Test case for create_namespaced_csi_storage_capacity

        """
        pass

    def test_delete_collection_namespaced_csi_storage_capacity(self) -> None:
        """Test case for delete_collection_namespaced_csi_storage_capacity

        """
        pass

    def test_delete_namespaced_csi_storage_capacity(self) -> None:
        """Test case for delete_namespaced_csi_storage_capacity

        """
        pass

    def test_get_api_resources(self) -> None:
        """Test case for get_api_resources

        """
        pass

    def test_list_csi_storage_capacity_for_all_namespaces(self) -> None:
        """Test case for list_csi_storage_capacity_for_all_namespaces

        """
        pass

    def test_list_namespaced_csi_storage_capacity(self) -> None:
        """Test case for list_namespaced_csi_storage_capacity

        """
        pass

    def test_patch_namespaced_csi_storage_capacity(self) -> None:
        """Test case for patch_namespaced_csi_storage_capacity

        """
        pass

    def test_read_namespaced_csi_storage_capacity(self) -> None:
        """Test case for read_namespaced_csi_storage_capacity

        """
        pass

    def test_replace_namespaced_csi_storage_capacity(self) -> None:
        """Test case for replace_namespaced_csi_storage_capacity

        """
        pass


if __name__ == '__main__':
    unittest.main()
