# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: release-1.26
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from kubernetes.client.models.v1beta2_flow_schema_condition import V1beta2FlowSchemaCondition

class TestV1beta2FlowSchemaCondition(unittest.TestCase):
    """V1beta2FlowSchemaCondition unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1beta2FlowSchemaCondition:
        """Test V1beta2FlowSchemaCondition
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1beta2FlowSchemaCondition`
        """
        model = V1beta2FlowSchemaCondition()
        if include_optional:
            return V1beta2FlowSchemaCondition(
                last_transition_time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                message = '',
                reason = '',
                status = '',
                type = ''
            )
        else:
            return V1beta2FlowSchemaCondition(
        )
        """

    def testV1beta2FlowSchemaCondition(self):
        """Test V1beta2FlowSchemaCondition"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
