# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: release-1.26
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from kubernetes.client.models.v1alpha1_pod_scheduling_status import V1alpha1PodSchedulingStatus

class TestV1alpha1PodSchedulingStatus(unittest.TestCase):
    """V1alpha1PodSchedulingStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1alpha1PodSchedulingStatus:
        """Test V1alpha1PodSchedulingStatus
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1alpha1PodSchedulingStatus`
        """
        model = V1alpha1PodSchedulingStatus()
        if include_optional:
            return V1alpha1PodSchedulingStatus(
                resource_claims = [
                    kubernetes.client.models.v1alpha1/resource_claim_scheduling_status.v1alpha1.ResourceClaimSchedulingStatus(
                        name = '', 
                        unsuitable_nodes = [
                            ''
                            ], )
                    ]
            )
        else:
            return V1alpha1PodSchedulingStatus(
        )
        """

    def testV1alpha1PodSchedulingStatus(self):
        """Test V1alpha1PodSchedulingStatus"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
