# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: release-1.26
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from kubernetes.client.api.resource_v1alpha1_api import ResourceV1alpha1Api


class TestResourceV1alpha1Api(unittest.TestCase):
    """ResourceV1alpha1Api unit test stubs"""

    def setUp(self) -> None:
        self.api = ResourceV1alpha1Api()

    def tearDown(self) -> None:
        pass

    def test_create_namespaced_pod_scheduling(self) -> None:
        """Test case for create_namespaced_pod_scheduling

        """
        pass

    def test_create_namespaced_resource_claim(self) -> None:
        """Test case for create_namespaced_resource_claim

        """
        pass

    def test_create_namespaced_resource_claim_template(self) -> None:
        """Test case for create_namespaced_resource_claim_template

        """
        pass

    def test_create_resource_class(self) -> None:
        """Test case for create_resource_class

        """
        pass

    def test_delete_collection_namespaced_pod_scheduling(self) -> None:
        """Test case for delete_collection_namespaced_pod_scheduling

        """
        pass

    def test_delete_collection_namespaced_resource_claim(self) -> None:
        """Test case for delete_collection_namespaced_resource_claim

        """
        pass

    def test_delete_collection_namespaced_resource_claim_template(self) -> None:
        """Test case for delete_collection_namespaced_resource_claim_template

        """
        pass

    def test_delete_collection_resource_class(self) -> None:
        """Test case for delete_collection_resource_class

        """
        pass

    def test_delete_namespaced_pod_scheduling(self) -> None:
        """Test case for delete_namespaced_pod_scheduling

        """
        pass

    def test_delete_namespaced_resource_claim(self) -> None:
        """Test case for delete_namespaced_resource_claim

        """
        pass

    def test_delete_namespaced_resource_claim_template(self) -> None:
        """Test case for delete_namespaced_resource_claim_template

        """
        pass

    def test_delete_resource_class(self) -> None:
        """Test case for delete_resource_class

        """
        pass

    def test_get_api_resources(self) -> None:
        """Test case for get_api_resources

        """
        pass

    def test_list_namespaced_pod_scheduling(self) -> None:
        """Test case for list_namespaced_pod_scheduling

        """
        pass

    def test_list_namespaced_resource_claim(self) -> None:
        """Test case for list_namespaced_resource_claim

        """
        pass

    def test_list_namespaced_resource_claim_template(self) -> None:
        """Test case for list_namespaced_resource_claim_template

        """
        pass

    def test_list_pod_scheduling_for_all_namespaces(self) -> None:
        """Test case for list_pod_scheduling_for_all_namespaces

        """
        pass

    def test_list_resource_claim_for_all_namespaces(self) -> None:
        """Test case for list_resource_claim_for_all_namespaces

        """
        pass

    def test_list_resource_claim_template_for_all_namespaces(self) -> None:
        """Test case for list_resource_claim_template_for_all_namespaces

        """
        pass

    def test_list_resource_class(self) -> None:
        """Test case for list_resource_class

        """
        pass

    def test_patch_namespaced_pod_scheduling(self) -> None:
        """Test case for patch_namespaced_pod_scheduling

        """
        pass

    def test_patch_namespaced_pod_scheduling_status(self) -> None:
        """Test case for patch_namespaced_pod_scheduling_status

        """
        pass

    def test_patch_namespaced_resource_claim(self) -> None:
        """Test case for patch_namespaced_resource_claim

        """
        pass

    def test_patch_namespaced_resource_claim_status(self) -> None:
        """Test case for patch_namespaced_resource_claim_status

        """
        pass

    def test_patch_namespaced_resource_claim_template(self) -> None:
        """Test case for patch_namespaced_resource_claim_template

        """
        pass

    def test_patch_resource_class(self) -> None:
        """Test case for patch_resource_class

        """
        pass

    def test_read_namespaced_pod_scheduling(self) -> None:
        """Test case for read_namespaced_pod_scheduling

        """
        pass

    def test_read_namespaced_pod_scheduling_status(self) -> None:
        """Test case for read_namespaced_pod_scheduling_status

        """
        pass

    def test_read_namespaced_resource_claim(self) -> None:
        """Test case for read_namespaced_resource_claim

        """
        pass

    def test_read_namespaced_resource_claim_status(self) -> None:
        """Test case for read_namespaced_resource_claim_status

        """
        pass

    def test_read_namespaced_resource_claim_template(self) -> None:
        """Test case for read_namespaced_resource_claim_template

        """
        pass

    def test_read_resource_class(self) -> None:
        """Test case for read_resource_class

        """
        pass

    def test_replace_namespaced_pod_scheduling(self) -> None:
        """Test case for replace_namespaced_pod_scheduling

        """
        pass

    def test_replace_namespaced_pod_scheduling_status(self) -> None:
        """Test case for replace_namespaced_pod_scheduling_status

        """
        pass

    def test_replace_namespaced_resource_claim(self) -> None:
        """Test case for replace_namespaced_resource_claim

        """
        pass

    def test_replace_namespaced_resource_claim_status(self) -> None:
        """Test case for replace_namespaced_resource_claim_status

        """
        pass

    def test_replace_namespaced_resource_claim_template(self) -> None:
        """Test case for replace_namespaced_resource_claim_template

        """
        pass

    def test_replace_resource_class(self) -> None:
        """Test case for replace_resource_class

        """
        pass


if __name__ == '__main__':
    unittest.main()
