# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: release-1.26
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from kubernetes.client.models.v1beta2_group_subject import V1beta2GroupSubject

class TestV1beta2GroupSubject(unittest.TestCase):
    """V1beta2GroupSubject unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1beta2GroupSubject:
        """Test V1beta2GroupSubject
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1beta2GroupSubject`
        """
        model = V1beta2GroupSubject()
        if include_optional:
            return V1beta2GroupSubject(
                name = ''
            )
        else:
            return V1beta2GroupSubject(
                name = '',
        )
        """

    def testV1beta2GroupSubject(self):
        """Test V1beta2GroupSubject"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
