# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: release-1.26
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from kubernetes.client.models.v1alpha1_resource_claim_consumer_reference import V1alpha1ResourceClaimConsumerReference

class TestV1alpha1ResourceClaimConsumerReference(unittest.TestCase):
    """V1alpha1ResourceClaimConsumerReference unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1alpha1ResourceClaimConsumerReference:
        """Test V1alpha1ResourceClaimConsumerReference
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1alpha1ResourceClaimConsumerReference`
        """
        model = V1alpha1ResourceClaimConsumerReference()
        if include_optional:
            return V1alpha1ResourceClaimConsumerReference(
                api_group = '',
                name = '',
                resource = '',
                uid = ''
            )
        else:
            return V1alpha1ResourceClaimConsumerReference(
                name = '',
                resource = '',
                uid = '',
        )
        """

    def testV1alpha1ResourceClaimConsumerReference(self):
        """Test V1alpha1ResourceClaimConsumerReference"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
