# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: release-1.26
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from kubernetes.client.models.v1beta2_priority_level_configuration import V1beta2PriorityLevelConfiguration

class TestV1beta2PriorityLevelConfiguration(unittest.TestCase):
    """V1beta2PriorityLevelConfiguration unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1beta2PriorityLevelConfiguration:
        """Test V1beta2PriorityLevelConfiguration
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1beta2PriorityLevelConfiguration`
        """
        model = V1beta2PriorityLevelConfiguration()
        if include_optional:
            return V1beta2PriorityLevelConfiguration(
                api_version = '',
                kind = '',
                metadata = kubernetes.client.models.v1/object_meta.v1.ObjectMeta(
                    annotations = {
                        'key' : ''
                        }, 
                    creation_timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    deletion_grace_period_seconds = 56, 
                    deletion_timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    finalizers = [
                        ''
                        ], 
                    generate_name = '', 
                    generation = 56, 
                    labels = {
                        'key' : ''
                        }, 
                    managed_fields = [
                        kubernetes.client.models.v1/managed_fields_entry.v1.ManagedFieldsEntry(
                            api_version = '', 
                            fields_type = '', 
                            fields_v1 = kubernetes.client.models.fields_v1.fieldsV1(), 
                            manager = '', 
                            operation = '', 
                            subresource = '', 
                            time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                        ], 
                    name = '', 
                    namespace = '', 
                    owner_references = [
                        kubernetes.client.models.v1/owner_reference.v1.OwnerReference(
                            api_version = '', 
                            block_owner_deletion = True, 
                            controller = True, 
                            kind = '', 
                            name = '', 
                            uid = '', )
                        ], 
                    resource_version = '', 
                    self_link = '', 
                    uid = '', ),
                spec = kubernetes.client.models.v1beta2/priority_level_configuration_spec.v1beta2.PriorityLevelConfigurationSpec(
                    limited = kubernetes.client.models.v1beta2/limited_priority_level_configuration.v1beta2.LimitedPriorityLevelConfiguration(
                        assured_concurrency_shares = 56, 
                        borrowing_limit_percent = 56, 
                        lendable_percent = 56, 
                        limit_response = kubernetes.client.models.v1beta2/limit_response.v1beta2.LimitResponse(
                            queuing = kubernetes.client.models.v1beta2/queuing_configuration.v1beta2.QueuingConfiguration(
                                hand_size = 56, 
                                queue_length_limit = 56, 
                                queues = 56, ), 
                            type = '', ), ), 
                    type = '', ),
                status = kubernetes.client.models.v1beta2/priority_level_configuration_status.v1beta2.PriorityLevelConfigurationStatus(
                    conditions = [
                        kubernetes.client.models.v1beta2/priority_level_configuration_condition.v1beta2.PriorityLevelConfigurationCondition(
                            last_transition_time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            message = '', 
                            reason = '', 
                            status = '', 
                            type = '', )
                        ], )
            )
        else:
            return V1beta2PriorityLevelConfiguration(
        )
        """

    def testV1beta2PriorityLevelConfiguration(self):
        """Test V1beta2PriorityLevelConfiguration"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
