# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: release-1.26
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from kubernetes.client.models.v1beta2_user_subject import V1beta2UserSubject

class TestV1beta2UserSubject(unittest.TestCase):
    """V1beta2UserSubject unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1beta2UserSubject:
        """Test V1beta2UserSubject
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1beta2UserSubject`
        """
        model = V1beta2UserSubject()
        if include_optional:
            return V1beta2UserSubject(
                name = ''
            )
        else:
            return V1beta2UserSubject(
                name = '',
        )
        """

    def testV1beta2UserSubject(self):
        """Test V1beta2UserSubject"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
