# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: release-1.26
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from kubernetes.client.api.networking_v1alpha1_api import NetworkingV1alpha1Api


class TestNetworkingV1alpha1Api(unittest.TestCase):
    """NetworkingV1alpha1Api unit test stubs"""

    def setUp(self) -> None:
        self.api = NetworkingV1alpha1Api()

    def tearDown(self) -> None:
        pass

    def test_create_cluster_cidr(self) -> None:
        """Test case for create_cluster_cidr

        """
        pass

    def test_delete_cluster_cidr(self) -> None:
        """Test case for delete_cluster_cidr

        """
        pass

    def test_delete_collection_cluster_cidr(self) -> None:
        """Test case for delete_collection_cluster_cidr

        """
        pass

    def test_get_api_resources(self) -> None:
        """Test case for get_api_resources

        """
        pass

    def test_list_cluster_cidr(self) -> None:
        """Test case for list_cluster_cidr

        """
        pass

    def test_patch_cluster_cidr(self) -> None:
        """Test case for patch_cluster_cidr

        """
        pass

    def test_read_cluster_cidr(self) -> None:
        """Test case for read_cluster_cidr

        """
        pass

    def test_replace_cluster_cidr(self) -> None:
        """Test case for replace_cluster_cidr

        """
        pass


if __name__ == '__main__':
    unittest.main()
