# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: release-1.26
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from kubernetes.client.models.v1alpha1_cluster_cidr_list import V1alpha1ClusterCIDRList

class TestV1alpha1ClusterCIDRList(unittest.TestCase):
    """V1alpha1ClusterCIDRList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1alpha1ClusterCIDRList:
        """Test V1alpha1ClusterCIDRList
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1alpha1ClusterCIDRList`
        """
        model = V1alpha1ClusterCIDRList()
        if include_optional:
            return V1alpha1ClusterCIDRList(
                api_version = '',
                items = [
                    kubernetes.client.models.v1alpha1/cluster_cidr.v1alpha1.ClusterCIDR(
                        api_version = '', 
                        kind = '', 
                        metadata = kubernetes.client.models.v1/object_meta.v1.ObjectMeta(
                            annotations = {
                                'key' : ''
                                }, 
                            creation_timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            deletion_grace_period_seconds = 56, 
                            deletion_timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            finalizers = [
                                ''
                                ], 
                            generate_name = '', 
                            generation = 56, 
                            labels = {
                                'key' : ''
                                }, 
                            managed_fields = [
                                kubernetes.client.models.v1/managed_fields_entry.v1.ManagedFieldsEntry(
                                    api_version = '', 
                                    fields_type = '', 
                                    fields_v1 = kubernetes.client.models.fields_v1.fieldsV1(), 
                                    manager = '', 
                                    operation = '', 
                                    subresource = '', 
                                    time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                                ], 
                            name = '', 
                            namespace = '', 
                            owner_references = [
                                kubernetes.client.models.v1/owner_reference.v1.OwnerReference(
                                    api_version = '', 
                                    block_owner_deletion = True, 
                                    controller = True, 
                                    kind = '', 
                                    name = '', 
                                    uid = '', )
                                ], 
                            resource_version = '', 
                            self_link = '', 
                            uid = '', ), 
                        spec = kubernetes.client.models.v1alpha1/cluster_cidr_spec.v1alpha1.ClusterCIDRSpec(
                            ipv4 = '', 
                            ipv6 = '', 
                            node_selector = kubernetes.client.models.v1/node_selector.v1.NodeSelector(
                                node_selector_terms = [
                                    kubernetes.client.models.v1/node_selector_term.v1.NodeSelectorTerm(
                                        match_expressions = [
                                            kubernetes.client.models.v1/node_selector_requirement.v1.NodeSelectorRequirement(
                                                key = '', 
                                                operator = '', 
                                                values = [
                                                    ''
                                                    ], )
                                            ], 
                                        match_fields = [
                                            kubernetes.client.models.v1/node_selector_requirement.v1.NodeSelectorRequirement(
                                                key = '', 
                                                operator = '', )
                                            ], )
                                    ], ), 
                            per_node_host_bits = 56, ), )
                    ],
                kind = '',
                metadata = kubernetes.client.models.v1/list_meta.v1.ListMeta(
                    continue = '', 
                    remaining_item_count = 56, 
                    resource_version = '', 
                    self_link = '', )
            )
        else:
            return V1alpha1ClusterCIDRList(
                items = [
                    kubernetes.client.models.v1alpha1/cluster_cidr.v1alpha1.ClusterCIDR(
                        api_version = '', 
                        kind = '', 
                        metadata = kubernetes.client.models.v1/object_meta.v1.ObjectMeta(
                            annotations = {
                                'key' : ''
                                }, 
                            creation_timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            deletion_grace_period_seconds = 56, 
                            deletion_timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            finalizers = [
                                ''
                                ], 
                            generate_name = '', 
                            generation = 56, 
                            labels = {
                                'key' : ''
                                }, 
                            managed_fields = [
                                kubernetes.client.models.v1/managed_fields_entry.v1.ManagedFieldsEntry(
                                    api_version = '', 
                                    fields_type = '', 
                                    fields_v1 = kubernetes.client.models.fields_v1.fieldsV1(), 
                                    manager = '', 
                                    operation = '', 
                                    subresource = '', 
                                    time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                                ], 
                            name = '', 
                            namespace = '', 
                            owner_references = [
                                kubernetes.client.models.v1/owner_reference.v1.OwnerReference(
                                    api_version = '', 
                                    block_owner_deletion = True, 
                                    controller = True, 
                                    kind = '', 
                                    name = '', 
                                    uid = '', )
                                ], 
                            resource_version = '', 
                            self_link = '', 
                            uid = '', ), 
                        spec = kubernetes.client.models.v1alpha1/cluster_cidr_spec.v1alpha1.ClusterCIDRSpec(
                            ipv4 = '', 
                            ipv6 = '', 
                            node_selector = kubernetes.client.models.v1/node_selector.v1.NodeSelector(
                                node_selector_terms = [
                                    kubernetes.client.models.v1/node_selector_term.v1.NodeSelectorTerm(
                                        match_expressions = [
                                            kubernetes.client.models.v1/node_selector_requirement.v1.NodeSelectorRequirement(
                                                key = '', 
                                                operator = '', 
                                                values = [
                                                    ''
                                                    ], )
                                            ], 
                                        match_fields = [
                                            kubernetes.client.models.v1/node_selector_requirement.v1.NodeSelectorRequirement(
                                                key = '', 
                                                operator = '', )
                                            ], )
                                    ], ), 
                            per_node_host_bits = 56, ), )
                    ],
        )
        """

    def testV1alpha1ClusterCIDRList(self):
        """Test V1alpha1ClusterCIDRList"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
