# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: release-1.26
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from kubernetes.client.models.v1alpha1_resource_class_parameters_reference import V1alpha1ResourceClassParametersReference

class TestV1alpha1ResourceClassParametersReference(unittest.TestCase):
    """V1alpha1ResourceClassParametersReference unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1alpha1ResourceClassParametersReference:
        """Test V1alpha1ResourceClassParametersReference
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1alpha1ResourceClassParametersReference`
        """
        model = V1alpha1ResourceClassParametersReference()
        if include_optional:
            return V1alpha1ResourceClassParametersReference(
                api_group = '',
                kind = '',
                name = '',
                namespace = ''
            )
        else:
            return V1alpha1ResourceClassParametersReference(
                kind = '',
                name = '',
        )
        """

    def testV1alpha1ResourceClassParametersReference(self):
        """Test V1alpha1ResourceClassParametersReference"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
